package de.passderdeutschenberge.ui.text

import androidx.annotation.StringRes
import de.passderdeutschenberge.R

// GENERIERT von tools/gen_strings.py - nicht von Hand aendern.
private val CHARACTER_TEXTS: Map<String, Int> = mapOf(
    "char_overath_bergisches_land" to R.string.char_overath_bergisches_land,
    "char_siebengebirge_bonn_rhein_sieg" to R.string.char_siebengebirge_bonn_rhein_sieg,
    "char_nordeifel_nationalpark_eifel" to R.string.char_nordeifel_nationalpark_eifel,
    "char_ahrtal_ahrgebirge" to R.string.char_ahrtal_ahrgebirge,
    "char_osteifel_laacher_see_hohe_eifel" to R.string.char_osteifel_laacher_see_hohe_eifel,
    "char_westerwald_siegerland" to R.string.char_westerwald_siegerland,
    "char_sauerland_rothaargebirge" to R.string.char_sauerland_rothaargebirge,
    "char_teutoburger_wald_egge_weserbergland" to R.string.char_teutoburger_wald_egge_weserbergland,
    "char_mittelrhein_koblenz_loreley" to R.string.char_mittelrhein_koblenz_loreley,
    "char_untermosel" to R.string.char_untermosel,
    "char_vulkaneifel" to R.string.char_vulkaneifel,
    "char_hunsrueck" to R.string.char_hunsrueck,
    "char_taunus_rheingau" to R.string.char_taunus_rheingau,
    "char_lahntal_mittelhessen" to R.string.char_lahntal_mittelhessen,
    "char_mittelmosel" to R.string.char_mittelmosel,
    "char_obermosel_trier" to R.string.char_obermosel_trier,
    "char_saarland" to R.string.char_saarland,
    "char_nordhessen_kellerwald_habichtswald" to R.string.char_nordhessen_kellerwald_habichtswald,
    "char_vogelsberg" to R.string.char_vogelsberg,
    "char_rhoen" to R.string.char_rhoen,
    "char_pfaelzerwald_dahner_felsenland" to R.string.char_pfaelzerwald_dahner_felsenland,
    "char_odenwald_bergstrasse" to R.string.char_odenwald_bergstrasse,
    "char_spessart" to R.string.char_spessart,
    "char_lueneburger_heide" to R.string.char_lueneburger_heide,
    "char_harz" to R.string.char_harz,
    "char_thueringer_wald_eisenach" to R.string.char_thueringer_wald_eisenach,
    "char_hainich_eichsfeld_kyffhaeuser" to R.string.char_hainich_eichsfeld_kyffhaeuser,
    "char_saale_unstrut_thueringer_becken" to R.string.char_saale_unstrut_thueringer_becken,
    "char_frankenwald" to R.string.char_frankenwald,
    "char_fichtelgebirge" to R.string.char_fichtelgebirge,
    "char_fraenkische_schweiz" to R.string.char_fraenkische_schweiz,
    "char_franken_altmuehltal_bayerischer_jura" to R.string.char_franken_altmuehltal_bayerischer_jura,
    "char_schwaebische_alb_nord_west" to R.string.char_schwaebische_alb_nord_west,
    "char_schwaebische_alb_sued_donautal" to R.string.char_schwaebische_alb_sued_donautal,
    "char_nordschwarzwald" to R.string.char_nordschwarzwald,
    "char_mittlerer_schwarzwald" to R.string.char_mittlerer_schwarzwald,
    "char_suedschwarzwald" to R.string.char_suedschwarzwald,
    "char_bodensee_hegau" to R.string.char_bodensee_hegau,
    "char_erzgebirge" to R.string.char_erzgebirge,
    "char_saechsische_schweiz" to R.string.char_saechsische_schweiz,
    "char_dresden_elbland" to R.string.char_dresden_elbland,
    "char_vogtland_oberlausitz_zittauer_gebirge" to R.string.char_vogtland_oberlausitz_zittauer_gebirge,
    "char_bayerischer_wald" to R.string.char_bayerischer_wald,
    "char_allgaeuer_alpen" to R.string.char_allgaeuer_alpen,
    "char_ammergauer_alpen_fuessen" to R.string.char_ammergauer_alpen_fuessen,
    "char_wetterstein_garmisch" to R.string.char_wetterstein_garmisch,
    "char_karwendel_estergebirge" to R.string.char_karwendel_estergebirge,
    "char_bayerische_voralpen_tegernsee_walchensee" to R.string.char_bayerische_voralpen_tegernsee_walchensee,
    "char_chiemgauer_alpen" to R.string.char_chiemgauer_alpen,
    "char_berchtesgadener_alpen" to R.string.char_berchtesgadener_alpen,
    "char_brandenburg_flaeming_spreewald" to R.string.char_brandenburg_flaeming_spreewald,
    "char_berlin_potsdam" to R.string.char_berlin_potsdam,
    "char_mecklenburgische_seenplatte" to R.string.char_mecklenburgische_seenplatte,
    "char_schleswig_holstein_holsteinische_schweiz" to R.string.char_schleswig_holstein_holsteinische_schweiz,
    "char_ruegen_jasmund_ostseekueste" to R.string.char_ruegen_jasmund_ostseekueste,
    "char_nordseekueste_inseln" to R.string.char_nordseekueste_inseln,
    "char_sammlungen_herausforderungen" to R.string.char_sammlungen_herausforderungen,
)

/** Charaktertext einer Grossregion; 0, wenn unbekannt. */
@StringRes
fun characterTextRes(resName: String): Int = CHARACTER_TEXTS[resName] ?: 0
